version: "3"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "8081:4000"
    volumes:
      - .:/app
      - ./node_modules:/home/nodejs/node_modules
      - ./project/.env:/app/.env
  nginx:
    image: nginx:latest
    links:
      - app
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: sample_db
