services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.data:/var/lib/postgresql/data
    ports:
      - 5432:5432
